### ISSUE TITLE
压力测试页面打不开

### ISSUE THREAD

**Issue by nodyang** [beetlex-io/BeetleX-Samples#7]
![image](https://user-images.githubusercontent.com/3090191/144372074-be7eee1d-9588-4158-bf0a-a17035a6368b.png)

![image](https://user-images.githubusercontent.com/3090191/144372139-b121dea7-f89a-4030-81a6-6881dbec2975.png)
![image](https://user-images.githubusercontent.com/3090191/144372151-85f6755b-37d2-4e92-87da-793db36fb965.png)

**Comment by beetlex-io** [comment]
把完全工程代码发一下，我试了一下没发现问题

**Comment by nodyang** [comment]
我就用得demo。难道是我浏览器的问题。。用的edge.

**Comment by nodyang** [comment]
我把各种加速器。代理关了。就OK了。。打扰了
